-- Insert all ingredients
INSERT INTO public.ingredients (name, unit, price_per_unit) VALUES
  ('Tarwebloem (bio)', 'kg', 3.02),
  ('Franse tarwebloem (bio)', 'kg', 3.94),
  ('Tarwemeel (bio)', 'kg', 2.76),
  ('Gerstmeel (bio)', 'kg', 3.79),
  ('Pompoenpitten (bio)', 'kg', 8.50),
  ('Boter', 'kg', 8.50),
  ('Speculoos', 'kg', 4.50),
  ('Lichtbruine suiker', 'kg', 2.98),
  ('Donkerbruine suiker', 'kg', 2.98),
  ('Kristalsuiker', 'kg', 2.38),
  ('Witte chocolade', 'kg', 15.00),
  ('Hazelnoten', 'kg', 14.72),
  ('Ei', 'stuks', 0.50),
  ('Eigeel', 'stuks', 0.50),
  ('Boekweitmeel', 'kg', 3.75),
  ('Amandelmeel', 'kg', 13.00),
  ('Amandelpasta', 'kg', 16.00),
  ('Bananen (bio)', 'kg', 2.50),
  ('Dadels (bio)', 'kg', 11.00),
  ('Kaneel (gemalen)', 'kg', 25.00),
  ('Havervlokken (bio)', 'kg', 3.00),
  ('Amandelen (bio)', 'kg', 11.00),
  ('Walnoten (bio)', 'kg', 13.00),
  ('Pecannoten (bio)', 'kg', 20.00),
  ('Zonnebloempitten (bio)', 'kg', 4.39),
  ('Olijfolie', 'kg', 8.50),
  ('Zout', 'kg', 3.50),
  ('Water', 'kg', 0.00),
  ('Desem', 'kg', 1.45),
  ('Verse basilicum', 'kg', 0.00),
  ('Speltbloem', 'kg', 3.00),
  ('Speltmeel', 'kg', 2.56),
  ('Speltdesem', 'kg', 1.96),
  ('Baking Soda', 'kg', 0.00),
  ('Baking Powder', 'kg', 0.00),
  ('Vanille', 'kg', 0.00),
  ('Cacaopoeder', 'kg', 17.44),
  ('Maizena', 'kg', 0.00),
  ('Espressopoeder', 'kg', 43.90),
  ('Donkere chocolade', 'kg', 15.90),
  ('Tijm (eetlepel)', 'stuks', 0.00),
  ('Citroenrasp (stuks)', 'stuks', 1.00),
  ('Citroensap', 'kg', 0.00),
  ('Yoghurt', 'kg', 3.39),
  ('Poedersuiker', 'kg', 4.00),
  ('Havervlokken', 'kg', 0.00),
  ('Eiwit', 'kg', 8.00),
  ('Gecondenseerde melk', 'kg', 8.29),
  ('Witte basterdsuiker', 'kg', 2.98),
  ('Poolish', 'kg', 0.00),
  ('Roggemeel', 'kg', 0.00),
  ('Roggebloem', 'kg', 0.00),
  ('Pizzabloem (00)', 'kg', 2.81),
  ('Maple syrup', 'kg', 19.00),
  ('Gist', 'kg', 0.00),
  ('Roomkaas', 'kg', 3.00),
  ('Slagroom', 'kg', 5.00),
  ('Fruitjam', 'kg', 6.00),
  ('Blauwe bessen', 'kg', 13.50),
  ('Melk', 'kg', 1.50);