// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchxlfdcwdmuwnrqlyae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaHhsZmRjd2RtdXducnFseWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4OTE2MDMsImV4cCI6MjA4NTQ2NzYwM30.9DFJw_NSVnuEtmQPQ3H1yKnIPDahfl9dQiZgN7evexU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});